[project]
name = 'Decentralized-Renewable-Energy-Trading-Network'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.automated-billing]
path = 'contracts/automated-billing.clar'
clarity_version = 2
epoch = 2.5

[contracts.energy-achievements]
path = 'contracts/energy-achievements.clar'
clarity_version = 2
epoch = 2.5

[contracts.energy-trading]
path = 'contracts/energy-trading.clar'
clarity_version = 2
epoch = 2.5

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
